spring:
  application: 
    name: PersonProfile
  jackson: 
    property-naming-strategy : SNAKE_CASE
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:h2:mem:person
    driverClassName: org.h2.Driver 
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect 
  h2:
    console:
      enabled: true
jwt:
  secret: IkpvaG4gRG9lIiwiYWRtaW4iO